### ISSUE TITLE
Switch to using AutoDoc for regenerating the manual, and the title page

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/gbnp#7]
Could also think about using the `extract_examples` option to replace the current machinery for converting examples into tests. However, that doesn't by itself with removing the timing output from the examples. So it is not a priority.

**Comment by RussWoodroofe** [comment]
@fingolfin, I notice that gbnp's manual is missing the css and js file.  Is this linked to not using AutoDoc?

**Comment by alex-konovalov** [comment]
They used GAPDoc, but did not include those files properly.

**Comment by fingolfin** [comment]
Did this now.
